services:
  telebot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telebot
    env_file:
      - .env
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
