version: '3.8'

services:
  redis:
    image: redis:7
    restart: always

  consumer:
    build: .
    command: python -u -m consumers.consumer
    environment:
      - PYTHONPATH=/app
      - REDIS_HOST=redis
    depends_on:
      - redis

  analytics:
    build: .
    command: python -u analytics/analytics_api.py
    ports:
      - "5001:5001"
    environment:
      - PYTHONPATH=/app
      - REDIS_HOST=redis
    depends_on:
      - redis