services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - my-shared-network

  consumer:
    build: .
    command: python -u -m consumers.consumer
    environment:
      - PYTHONPATH=/app
    depends_on:
      - redis
    networks:
      - my-shared-network

networks:
  my-shared-network:
    external: true