version: "3.9"

services:
  resend-wrapper:
    build: .
    container_name: resend-wrapper
    env_file:
      - .env
    networks:
      - my-shared-network

networks:
  my-shared-network:
    external: true