version: '3.8'

services:
  rooms-db:
    image: mysql:8.0
    container_name: rooms-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rooms
      TZ: Asia/Singapore
    ports:
      - "3307:3306"
    volumes:
      - rooms_mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  rooms-service:
    build: .
    container_name: rooms-service
    restart: always
    depends_on:
      - rooms-db
    environment:
      DB_HOST: rooms-db
      DB_PORT: 3306
      DB_NAME: rooms
      DB_USER: root
      DB_PASSWORD: root
      TZ: Asia/Singapore
    ports:
      - "5003:5003"

volumes:
  rooms_mysql_data: