version: "3.9"

services:
  payments-postgres:
    image: postgres:16
    container_name: payments_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: payments_db
      POSTGRES_USER: payments_user
      POSTGRES_PASSWORD: payments_pass
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  payment-service:
    build: .
    container_name: payment_service
    restart: unless-stopped
    depends_on:
      - payments-postgres
    environment:
      DB_HOST: payments-postgres
      DB_PORT: 5432
      DB_NAME: payments_db
      DB_USER: payments_user
      DB_PASSWORD: payments_pass
      ETHERSCAN_V2_HOST: https://api.etherscan.io/v2/api
      CHAIN_ID: 84532
      ETHERSCAN_API_KEY: JEXSFHW2AM4BARRDYZ838FV3I6QE6D6H9X
      PAY_TO_ADDRESS: 0x5c6688532A27492DA6C534a37cedE11A86823152
      TOKEN_CONTRACT: 0xbbD47B1eAdb7513a08c26C68E2669f4FE3B7Eae7
      RPC_URL: https://sepolia.base.org
      REFUND_WALLET_ADDRESS: 0x5c6688532A27492DA6C534a37cedE11A86823152
      REFUND_PRIVATE_KEY: 2af0aa05f3c59cb84c296ab0208bba53b31edbf0ef0571facd246e52e4455a36
      TOKEN_DECIMALS: 6
      TIME_WINDOW_SECONDS: 3600
    ports:
      - "8080:8080"

volumes:
  postgres_data: